const SCREEN_WIDTH = 432;
const SCREEN_HEIGHT = 912;

const SPRITE_DIR = 'src/assets/sprites/';
const MAPS_DIR = 'src/assets/maps/';

enum Esprites{PLAYER, BACKW_PLANE, BASIC_PLANE, HELICOPTER, BIROTOR_PLANE, 
              EXPLOSION1, BULLET1, BULLET_ENEM1, FIGHTER_JET, HIT_LIGHT}

enum EshootTypes{NONE, PLAYER, BASIC, DOUBLE, TRIPLE, AIMED_BASIC}
