const SCREEN_WIDTH = 432;
const SCREEN_HEIGHT = 912;

const SPRITE_DIR = 'src/assets/sprites/';
const MAPS_DIR = 'src/assets/maps/';

const PLANE_DESTROY_DELAY = 200;

enum Esprites{PLAYER, BACKW_PLANE, BASIC_PLANE, HELICOPTER, BIROTOR_PLANE, FIGHTER_JET,
              PLAYER_F, BACKW_PLANE_F, BASIC_PLANE_F, HELICOPTER_F, BIROTOR_PLANE_F,
              EXPLOSION1, BULLET1, BULLET_ENEM1,  HIT_LIGHT}

enum EshootTypes{NONE, PLAYER, BASIC, DOUBLE, TRIPLE, AIMED_BASIC}
enum EmoveTypes{GROUNDED, LINEAR, ZIGZAG, WAVE}
