const SCREEN_WIDTH = 432;
const SCREEN_HEIGHT = 912;

const SPRITE_DIR = 'src/assets/sprites/';
const MAPS_DIR = 'src/assets/maps/';

// probablity from 0 to 1 of enemy dropping power up
const POWER_UP_DROP_ROBABILITY = 0.1; 

const PLANE_DESTROY_DELAY = 200;
const BIG_PLANE_WIDTH = 45;

enum Esounds {BG_MUSIC, MENU_MUSIC, DEFEAT, VICTORY, PLAYER_HURT, BUTTON, TAKE_OFF, PLAYER_SHOT, EXPLOSION1, EXPLOSION_MEDIUM, POW_PICKUP, SHIELD_PICKUP, DMG_PUP_PICKUP}

enum Esprites{PLAYER,  BACKW_PLANE, BASIC_PLANE, HELICOPTER, BIROTOR_PLANE, FIGHTER_JET,
              PLAYER_F, BACKW_PLANE_F, BASIC_PLANE_F, HELICOPTER_F, BIROTOR_PLANE_F,
              EXPLOSION1, EXPLOSION_MEDIUM, BULLET1, BULLET_DMG_BOOST, BULLET_ENEM1,  HIT_LIGHT,
              POW_POWERUP, SHIELD, SHIELD_POWERUP, DAMAGE_POWERUP}

enum EshootTypes{NONE, PLAYER, PLAYER_DMG_BOOST, PLAYER_F, PLAYER_DMG_BOOST_F, BASIC, BASIC_F, DOUBLE, DOUBLE_F, TRIPLE, TRIPLE_F, AIMED_LINEAR}
enum EmoveTypes{GROUNDED, LINEAR, ZIGZAG, WAVE}
